### ISSUE TITLE
create a 'credit' page

### ISSUE THREAD

**Issue by kyzh** [itchix/OpenFoodFacts-android#16]
it would be nice to have a place where you could take credit for your work, maybe put a link to OFF and a word on the licence the picture endup as.

**Comment by itchix** [comment]
Of course, I'm on it :)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/22603514/027c819e-ea48-11e6-8289-55ea29fe2372.png)
